### ISSUE TITLE
build docker-compose help

### ISSUE THREAD

**Issue by cocolabombe0** [devalx/docker-teamspeak3#10]
Hi, Can you help me with this transformed docker in docker-compose.

```
# create the data container
docker run --name=ts3-data --entrypoint /bin/true devalx/docker-teamspeak3:latest
# Now start the actual TS3-Server
docker run --name=ts3 -d --volumes-from ts3-data -p 9987:9987/udp -p 30033:30033 -p 10011:10011 devalx/docker-teamspeak3:latest
```

How to change the /home/ts3/data/query_ip_whitelist.txt file to add ip?
I have a TeamSpeak also ban interface and I'm getting when I connect.

**Comment by devalx** [comment]
If you want to use docker-compose use something like this:

```
version: '2'
services:
### Teamspeak 3
  ts3:
    restart: always
    image: devalx/docker-teamspeak3:latest
    container_name: ts3
    ports:
     - "9987:9987/udp"
     - "30033:30033"
     - "10011:10011"
    volumes:
     - ts3-data:/home/ts3/data
volumes:
  ts3-data:
    driver: local

```
